name: steph-hagadorn
favicon: null
layout_spectrum: 0.664911761181429
typography_spectrum: 0.9828406283631921
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5085476662497967
  lightness: 0.9153949348255992
  saturation: 0.06353315082378685
  rhythmicContrast: 0.9989379041362554
purpose: []
