name: steph-hagadorn
favicon: null
layout_spectrum: 0.25279
typography_spectrum: 0.89193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0092ea'
    - '#e2a747'
    - '#000000'
    - '#635761'
    - '#ffffff'
  brandStrength: 0.375
  lightness: 0.9153949348255992
  saturation: 0.1875
  rhythmicContrast: 0.9989379041362554
purpose: []
